on:
  push:
    branches:
      - main
jobs:
  infrastructure:
    name: "Infrastructure"
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: data-visitor-334805
      TF_BUCKET: cf7e3478-6c37-4d0f-910c-87e6bda48191
      DEPLOY_BUCKET: b3f69dd1-9c32-43e9-9446-9e3567075f5f
      DNS_NAME: piper.codes
    steps:
      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install terraform -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.BUILD_KEY_PROD }}
          export_default_credentials: true
      - name: Terraform Init
        working-directory: ./infrastructure
        run: terraform init -backend-config="bucket=${{ env.TF_BUCKET }}"
      - name: Terraform Apply
        working-directory: ./infrastructure
        run: |
          terraform apply -auto-approve -no-color -var "project_id=${{ env.PROJECT_ID }}" -var "dns_name=${{ env.DNS_NAME }}" \
          -var "deploy_bucket=${{ env.DEPLOY_BUCKET }}"
    outputs:
      deploy_bucket: ${{ env.DEPLOY_BUCKET }}
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs:
      - infrastructure
    env:
      PROJECT_ID: data-visitor-334805
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build website
        run: |
          yarn
          yarn build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.BUILD_KEY_PROD }}
          export_default_credentials: true
      - name: Deploy to bucket
        run: |
          gsutil rsync -avzrp build/ gs://${{ needs.infrastructure.outputs.deploy_bucket }}
